#
# These worlds cannot be donated from
# Format: comma separated world names
#
restricted-worlds: 

#
# Items that should be dropped into the void
#
restricted-items: 0,6,7,8,9,10,11,51,99

#
# The frequency of drops
#
drop-frequency: 45

 
